In [1]:
import torch

/home/vishu/.local/lib/python3.10/site-packages/tqdm/auto.py:22: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [7]:
input = torch.randn(size=(5,7))

In [3]:
input

tensor([[-0.1615,  0.4655,  0.7545,  0.7436],
        [ 1.0228, -0.1680,  0.9212,  0.0596],
        [-0.1881,  0.6316,  0.9590, -0.0392]])

In [8]:
another = torch.randn(size=(7,9))

In [10]:
(input @ another).shape

torch.Size([5, 9])

In [13]:
torch.matmul(input=input,other=another).shape

torch.Size([5, 9])

In [2]:
input = torch.Tensor(size=(2,4))

In [3]:
input

tensor([[-1.1112e-14,  4.5576e-41,  6.6261e-38,  4.5577e-41],
        [-1.1245e-14,  4.5576e-41,  6.6261e-38,  4.5577e-41]])

In [4]:
input.shape

torch.Size([2, 4])

In [5]:
synapes = torch.randn(size=(4,6))

In [11]:
hidden = (input @ synapes)

In [8]:
synapes2 = torch.randn(size=(6,1))

In [10]:
synapes2.shape

torch.Size([6, 1])

In [12]:
output = (hidden @ synapes2)

In [13]:
output

tensor([[-3.4369e-14],
        [-3.4780e-14]])

In [14]:
import torch.nn as nn

In [15]:
synapes1 = nn.Linear(4,6)
synapes1_2 = nn.Linear(6,6)

In [16]:
synapes2 = nn.Linear(6,1)

In [19]:
synapes2(synapes1(input))

tensor([[0.2355],
        [0.2355]], grad_fn=<AddmmBackward0>)

In [ ]:
# 2,4
[32,1,7,0]
[24,0,1,1]